# Healthcare Data Wrangling

In [ ]:
# this script improves the quality of the 1000_generic_medication_names_NHC.txt dataset
# this is a demo dataset storing the names and classes of 1000 medications
# the goal of this script is to create a CSV file storing medication names and classes...
# ... in two distinct columns, for each entry

In [1]:
# before importing any library, run the statements below in the terminal
# when installing any package, make sure to be in the proper environment!
# conda install anaconda::pandas

import pandas as pd

In [ ]:
# assign the path to the input and output file folders to a variable for reproducibility (and privacy)
input_folder_path = "path/to/input/file/folder/"
output_folder_path = "path/to/output/file/folder/"

In [3]:
# read a TXT into a data frame
df_med = pd.read_csv(input_folder_path+"1000_generic_medication_names_NHC.txt", sep="\t", header=None)
df_med

                                                     0
0         1. Acetaminophen Tablet (500 mg) - Analgesic
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...
4        5. Morphine Tablet (15 mg) - Opioid Analgesic
..                                                 ...
995  996. Alprostadil Urethral Suppository (250 mcg...
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...
997  998. Papaverine Injection (30 mg/mL) - Vasodil...
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...

[1000 rows x 1 columns]

## Brainstorming

In [4]:
# inspect the first item
df_med[0][0]

'1. Acetaminophen Tablet (500 mg) - Analgesic'

In [5]:
# check its data type
type(df_med[0][0])

str

In [6]:
# splitting strings by "." would ultimately leave leading/trailing spaces around the medication name field
# plus, some entries (e.g., the second-to-last entry) feature multiple full stops
# splitting by "." causes issues here
df_med[0][998].split(".")

['999', ' Yohimbine Tablet (5', '4 mg) - Alpha-2 Blocker']

In [7]:
# similarly, splitting strings by "-" would ultimately leave leading/trailing spaces around the medication class field
# plus, some entries (e.g., the 997th entry) feature multiple dashes
# splitting by "-" causes issues here
df_med[0][996].split("-")

['997. Phentolamine Injection (1 mg/mL) ', ' Alpha', 'Blocker']

In [ ]:
# to account for these issues, I'm spitting strings by ". " and ") - ", respectively

In [8]:
# split the string by the ". "
df_med[0][0].split(". ")

['1', 'Acetaminophen Tablet (500 mg) - Analgesic']

In [9]:
# check the resulting data type
type(df_med[0][0].split(". "))

list

In [10]:
# access its second part
df_med[0][0].split(". ")[1]

'Acetaminophen Tablet (500 mg) - Analgesic'

In [11]:
# I initially split this second part (of the '1. Acetaminophen Tablet (500 mg) - Analgesic' string) by the " - "
# i.e., split 'Acetaminophen Tablet (500 mg) - Analgesic' by " - "
df_med[0][0].split(". ")[1].split(" - ")

['Acetaminophen Tablet (500 mg)', 'Analgesic']

In [12]:
# however, I later noticed that there is a medication named 'Nystatin/Triamcinolone Topical Cream (100,000 units/g - 0.1%) - Antifungal/Corticosteroid Combination'
df_med[0][174]

'175. Nystatin/Triamcinolone Topical Cream (100,000 units/g - 0.1%) - Antifungal/Corticosteroid Combination'

In [ ]:
# to account for it, I'm splitting by ") - " instead of " - "
df_med[0][174].split(". ")[1].split(") - ")

['Nystatin/Triamcinolone Topical Cream (100,000 units/g - 0.1%',
 'Antifungal/Corticosteroid Combination']

In [14]:
# get the medication name, without the dosage
df_med[0][0].split(". ")[1].split(") - ")[1]

'Analgesic'

In [15]:
df_med[0][174].split(". ")[1].split(") - ")[1]

'Antifungal/Corticosteroid Combination'

## Solution

In [16]:
# create a column storing the medication name for each entry
df_med["med_name"] = df_med[0].apply(lambda x : x.split(". ")[1].split(") - ")[0].split(" (")[0])
df_med

,0,med_name
0,1. Acetaminophen Tablet (500 mg) - Analgesic,Acetaminophen Tablet
1,2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...,Ibuprofen Tablet
2,3. Aspirin Tablet (81 mg) - Platelet Aggregati...,Aspirin Tablet
3,4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...,Naproxen Tablet
4,5. Morphine Tablet (15 mg) - Opioid Analgesic,Morphine Tablet
...,...,...
995,996. Alprostadil Urethral Suppository (250 mcg...,Alprostadil Urethral Suppository
996,997. Phentolamine Injection (1 mg/mL) - Alpha-...,Phentolamine Injection
997,998. Papaverine Injection (30 mg/mL) - Vasodil...,Papaverine Injection
998,999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker,Yohimbine Tablet
999,1000. L-Arginine Tablet (500 mg) - Amino Acid ...,L-Arginine Tablet

In [17]:
# create a column storing the medication class for each entry
df_med["med_class"] = df_med[0].apply(lambda x : x.split(". ")[1].split(") - ")[1])
df_med

,0,med_name,med_class
0,1. Acetaminophen Tablet (500 mg) - Analgesic,Acetaminophen Tablet,Analgesic
1,2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...,Ibuprofen Tablet,Nonsteroidal Anti-Inflammatory Drug
2,3. Aspirin Tablet (81 mg) - Platelet Aggregati...,Aspirin Tablet,Platelet Aggregation Inhibitor
3,4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...,Naproxen Tablet,Nonsteroidal Anti-Inflammatory Drug
4,5. Morphine Tablet (15 mg) - Opioid Analgesic,Morphine Tablet,Opioid Analgesic
...,...,...,...
995,996. Alprostadil Urethral Suppository (250 mcg...,Alprostadil Urethral Suppository,Prostaglandin E1 Analog
996,997. Phentolamine Injection (1 mg/mL) - Alpha-...,Phentolamine Injection,Alpha-Blocker
997,998. Papaverine Injection (30 mg/mL) - Vasodil...,Papaverine Injection,Vasodilator
998,999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker,Yohimbine Tablet,Alpha-2 Blocker
999,1000. L-Arginine Tablet (500 mg) - Amino Acid ...,L-Arginine Tablet,Amino Acid Supplement

In [18]:
df_med = df_med[["med_name", "med_class"]]
df_med

                             med_name                            med_class
0                Acetaminophen Tablet                            Analgesic
1                    Ibuprofen Tablet  Nonsteroidal Anti-Inflammatory Drug
2                      Aspirin Tablet       Platelet Aggregation Inhibitor
3                     Naproxen Tablet  Nonsteroidal Anti-Inflammatory Drug
4                     Morphine Tablet                     Opioid Analgesic
..                                ...                                  ...
995  Alprostadil Urethral Suppository              Prostaglandin E1 Analog
996            Phentolamine Injection                        Alpha-Blocker
997              Papaverine Injection                          Vasodilator
998                  Yohimbine Tablet                      Alpha-2 Blocker
999                 L-Arginine Tablet                Amino Acid Supplement

[1000 rows x 2 columns]

In [19]:
# the (apparently) only remaining issue is at line 774
df_med["med_name"][772]

'Metoprolol Tablet(25 mg'

In [20]:
# since this is the (apparently) only remaining issue in the whole dataset...
# ... we can apply a one-row correction
df_med.loc[772, "med_name"] = df_med.loc[772, "med_name"].replace("(25 mg", "")
df_med["med_name"][772]

'Metoprolol Tablet'

In [ ]:
# write the data frame to a CSV file
df_med.to_csv(output_folder_path+"med_namenodosage_class.csv", index=False)