# Healthcare Data Wrangling

In [ ]:
# this script improves the quality of the 1000_generic_medication_names_NHC.txt dataset
# this is a demo dataset storing the names and classes of 1000 medications

In [1]:
# before importing any library, run the statements below in the terminal
# when installing any package, make sure to be in the proper environment!
# conda install anaconda::pandas

import pandas as pd

In [2]:
# assign the path to the input file folder to a variable for reproducibility (and privacy)
input_folder_path = "C:/Users/rguat/OneDrive/Desktop/data_analysis/python/python_for_healthcare/exercise_files/"

## 01: Practical Data Manipulation and Wrangling Pt. 1

In [3]:
# read a TXT into a data frame
df_med = pd.read_csv(input_folder_path+"1000_generic_medication_names_NHC.txt", sep="\t", header=None)
df_med

                                                     0
0         1. Acetaminophen Tablet (500 mg) - Analgesic
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...
4        5. Morphine Tablet (15 mg) - Opioid Analgesic
..                                                 ...
995  996. Alprostadil Urethral Suppository (250 mcg...
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...
997  998. Papaverine Injection (30 mg/mL) - Vasodil...
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...

[1000 rows x 1 columns]

In [4]:
# inspect the first item
df_med[0][0]

'1. Acetaminophen Tablet (500 mg) - Analgesic'

In [5]:
# check its data type
type(df_med[0][0])

str

In [ ]:
# I didn't include the following six cells "as-they-are" in 05_1

In [6]:
# split the string by the "."
df_med[0][0].split(".")

['1', ' Acetaminophen Tablet (500 mg) - Analgesic']

In [7]:
# check the resulting data type
type(df_med[0][0].split("."))

list

In [8]:
# split the string by the "-"
df_med[0][0].split("-")

['1. Acetaminophen Tablet (500 mg) ', ' Analgesic']

In [9]:
# check its data type
type(df_med[0][0].split("-"))

list

In [10]:
# access its first part
df_med[0][0].split("-")[0]

'1. Acetaminophen Tablet (500 mg) '

In [11]:
# access its seconds part
df_med[0][0].split("-")[1]

' Analgesic'

In [ ]:
# let's use these to tidy up the data set

In [12]:
# create a column storing the medication class for each entry
df_med["med_class"] = df_med[0].apply(lambda x : x.split("-")[1])
df_med

,0,med_class
0,1. Acetaminophen Tablet (500 mg) - Analgesic,Analgesic
1,2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...,Nonsteroidal Anti
2,3. Aspirin Tablet (81 mg) - Platelet Aggregati...,Platelet Aggregation Inhibitor
3,4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...,Nonsteroidal Anti
4,5. Morphine Tablet (15 mg) - Opioid Analgesic,Opioid Analgesic
...,...,...
995,996. Alprostadil Urethral Suppository (250 mcg...,Prostaglandin E1 Analog
996,997. Phentolamine Injection (1 mg/mL) - Alpha-...,Alpha
997,998. Papaverine Injection (30 mg/mL) - Vasodil...,Vasodilator
998,999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker,Alpha
999,1000. L-Arginine Tablet (500 mg) - Amino Acid ...,Arginine Tablet (500 mg)

In [13]:
# the 997th entry features two dashes!
df_med[0][996]

'997. Phentolamine Injection (1 mg/mL) - Alpha-Blocker'

In [14]:
# the same goes for the last entry
df_med[0][999] # df_med[0][999].split(".")[1]

'1000. L-Arginine Tablet (500 mg) - Amino Acid Supplement'

In [15]:
# the second-to-last entry features multiple full stops
df_med[0][998]

'999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker'

In [16]:
# splitting by "." causes issues here
df_med[0][998].split(".")

['999', ' Yohimbine Tablet (5', '4 mg) - Alpha-2 Blocker']

In [17]:
# to account for more than a full stop, use this
df_med[0][998].split(".", maxsplit=1)

['999', ' Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker']

In [18]:
# create a column storing the medication name (and dosage) for each entry
df_med["med_name"] = df_med[0].apply(lambda x: x.split(".", maxsplit=1)[1].split("-")[0])
df_med

,0,med_class,med_name
0,1. Acetaminophen Tablet (500 mg) - Analgesic,Analgesic,Acetaminophen Tablet (500 mg)
1,2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...,Nonsteroidal Anti,Ibuprofen Tablet (200 mg)
2,3. Aspirin Tablet (81 mg) - Platelet Aggregati...,Platelet Aggregation Inhibitor,Aspirin Tablet (81 mg)
3,4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...,Nonsteroidal Anti,Naproxen Tablet (250 mg)
4,5. Morphine Tablet (15 mg) - Opioid Analgesic,Opioid Analgesic,Morphine Tablet (15 mg)
...,...,...,...
995,996. Alprostadil Urethral Suppository (250 mcg...,Prostaglandin E1 Analog,Alprostadil Urethral Suppository (250 mcg)
996,997. Phentolamine Injection (1 mg/mL) - Alpha-...,Alpha,Phentolamine Injection (1 mg/mL)
997,998. Papaverine Injection (30 mg/mL) - Vasodil...,Vasodilator,Papaverine Injection (30 mg/mL)
998,999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker,Alpha,Yohimbine Tablet (5.4 mg)
999,1000. L-Arginine Tablet (500 mg) - Amino Acid ...,Arginine Tablet (500 mg),L

## 02: Practical Data Manipulation and Wrangling Pt. 2

In [19]:
# create two additional columns
# a column named 'combined', storing both the number and the medication name...
# ... and a column named 'med_class_2', storing medication names only
df_med[["combined", "med_class_2"]] = df_med[0].str.split("-", n=1, expand=True)
df_med

,0,med_class,med_name,combined,med_class_2
0,1. Acetaminophen Tablet (500 mg) - Analgesic,Analgesic,Acetaminophen Tablet (500 mg),1. Acetaminophen Tablet (500 mg),Analgesic
1,2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...,Nonsteroidal Anti,Ibuprofen Tablet (200 mg),2. Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,3. Aspirin Tablet (81 mg) - Platelet Aggregati...,Platelet Aggregation Inhibitor,Aspirin Tablet (81 mg),3. Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...,Nonsteroidal Anti,Naproxen Tablet (250 mg),4. Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,5. Morphine Tablet (15 mg) - Opioid Analgesic,Opioid Analgesic,Morphine Tablet (15 mg),5. Morphine Tablet (15 mg),Opioid Analgesic
...,...,...,...,...,...
995,996. Alprostadil Urethral Suppository (250 mcg...,Prostaglandin E1 Analog,Alprostadil Urethral Suppository (250 mcg),996. Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,997. Phentolamine Injection (1 mg/mL) - Alpha-...,Alpha,Phentolamine Injection (1 mg/mL),997. Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,998. Papaverine Injection (30 mg/mL) - Vasodil...,Vasodilator,Papaverine Injection (30 mg/mL),998. Papaverine Injection (30 mg/mL),Vasodilator
998,999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker,Alpha,Yohimbine Tablet (5.4 mg),999. Yohimbine Tablet (5.4 mg),Alpha-2 Blocker
999,1000. L-Arginine Tablet (500 mg) - Amino Acid ...,Arginine Tablet (500 mg),L,1000. L,Arginine Tablet (500 mg) - Amino Acid Supplement

In [20]:
# create a second data frame by filtering 'df_med' to retain only the 'med_name' and 'med_class_2' columns
df_med_2 = df_med[["med_name", "med_class_2"]]
df_med_2

,med_name,med_class_2
0,Acetaminophen Tablet (500 mg),Analgesic
1,Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,Morphine Tablet (15 mg),Opioid Analgesic
...,...,...
995,Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,Papaverine Injection (30 mg/mL),Vasodilator
998,Yohimbine Tablet (5.4 mg),Alpha-2 Blocker
999,L,Arginine Tablet (500 mg) - Amino Acid Supplement

In [21]:
# rename the 'med_class_2' column to 'med_class'
df_med_2.rename(columns={"med_class_2": "med_class"}, inplace=True)
df_med_2

,med_name,med_class
0,Acetaminophen Tablet (500 mg),Analgesic
1,Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,Morphine Tablet (15 mg),Opioid Analgesic
...,...,...
995,Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,Papaverine Injection (30 mg/mL),Vasodilator
998,Yohimbine Tablet (5.4 mg),Alpha-2 Blocker
999,L,Arginine Tablet (500 mg) - Amino Acid Supplement

In [22]:
# remove the last, problematic entry...
df_med_2 = df_med_2.drop(999)
df_med_2

,med_name,med_class
0,Acetaminophen Tablet (500 mg),Analgesic
1,Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,Morphine Tablet (15 mg),Opioid Analgesic
...,...,...
994,Vardenafil Tablet (5 mg),Phosphodiesterase Type 5 Inhibitor
995,Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,Papaverine Injection (30 mg/mL),Vasodilator
998,Yohimbine Tablet (5.4 mg),Alpha-2 Blocker

In [23]:
# write the data frame to a CSV file
df_med_2.to_csv("med_name_and_class.csv", index=False)

In [24]:
# check everything is fine
pd.read_csv("med_name_and_class.csv")

,med_name,med_class
0,Acetaminophen Tablet (500 mg),Analgesic
1,Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,Morphine Tablet (15 mg),Opioid Analgesic
...,...,...
994,Vardenafil Tablet (5 mg),Phosphodiesterase Type 5 Inhibitor
995,Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,Papaverine Injection (30 mg/mL),Vasodilator
998,Yohimbine Tablet (5.4 mg),Alpha-2 Blocker

In [25]:
df_med_3 = df_med.copy()
df_med_3

,0,med_class,med_name,combined,med_class_2
0,1. Acetaminophen Tablet (500 mg) - Analgesic,Analgesic,Acetaminophen Tablet (500 mg),1. Acetaminophen Tablet (500 mg),Analgesic
1,2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...,Nonsteroidal Anti,Ibuprofen Tablet (200 mg),2. Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,3. Aspirin Tablet (81 mg) - Platelet Aggregati...,Platelet Aggregation Inhibitor,Aspirin Tablet (81 mg),3. Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...,Nonsteroidal Anti,Naproxen Tablet (250 mg),4. Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,5. Morphine Tablet (15 mg) - Opioid Analgesic,Opioid Analgesic,Morphine Tablet (15 mg),5. Morphine Tablet (15 mg),Opioid Analgesic
...,...,...,...,...,...
995,996. Alprostadil Urethral Suppository (250 mcg...,Prostaglandin E1 Analog,Alprostadil Urethral Suppository (250 mcg),996. Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,997. Phentolamine Injection (1 mg/mL) - Alpha-...,Alpha,Phentolamine Injection (1 mg/mL),997. Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,998. Papaverine Injection (30 mg/mL) - Vasodil...,Vasodilator,Papaverine Injection (30 mg/mL),998. Papaverine Injection (30 mg/mL),Vasodilator
998,999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker,Alpha,Yohimbine Tablet (5.4 mg),999. Yohimbine Tablet (5.4 mg),Alpha-2 Blocker
999,1000. L-Arginine Tablet (500 mg) - Amino Acid ...,Arginine Tablet (500 mg),L,1000. L,Arginine Tablet (500 mg) - Amino Acid Supplement

In [26]:
df_med_3 = df_med_3.drop(columns=[0, "med_class", "combined"])
df_med_3

,med_name,med_class_2
0,Acetaminophen Tablet (500 mg),Analgesic
1,Ibuprofen Tablet (200 mg),Nonsteroidal Anti-Inflammatory Drug
2,Aspirin Tablet (81 mg),Platelet Aggregation Inhibitor
3,Naproxen Tablet (250 mg),Nonsteroidal Anti-Inflammatory Drug
4,Morphine Tablet (15 mg),Opioid Analgesic
...,...,...
995,Alprostadil Urethral Suppository (250 mcg),Prostaglandin E1 Analog
996,Phentolamine Injection (1 mg/mL),Alpha-Blocker
997,Papaverine Injection (30 mg/mL),Vasodilator
998,Yohimbine Tablet (5.4 mg),Alpha-2 Blocker
999,L,Arginine Tablet (500 mg) - Amino Acid Supplement

## Let's Try It Myself

In [6]:
# split the string by the " ("
df_med[0][0].split(" (")

['1. Acetaminophen Tablet', '500 mg) - Analgesic']

In [7]:
# split the string by the " ("
df_med[0][995].split(" (")

['996. Alprostadil Urethral Suppository', '250 mcg) - Prostaglandin E1 Analog']

In [ ]:
# split the string by the " (", and then by ". "
df_med[0][995].split(" (")[0].split(". ")

['996', 'Alprostadil Urethral Suppository']

In [14]:
# split the string by the " (", then by ". ", and then by " "
df_med[0][995].split(" (")[0].split(". ")[1].split(" ", maxsplit=1)

['Alprostadil', 'Urethral Suppository']

In [ ]:
# get the medication name
df_med[0][995].split(" (")[0].split(". ")[1].split(" ", maxsplit=1)[0]

'Alprostadil'

In [17]:
df_med[0][0].split(" (")[0].split(". ")[1].split(" ", maxsplit=1)[0]

'Acetaminophen'

In [16]:
# get the medication 'format'
df_med[0][995].split(" (")[0].split(". ")[1].split(" ", maxsplit=1)[1]

'Urethral Suppository'

In [18]:
df_med[0][0].split(" (")[0].split(". ")[1].split(" ", maxsplit=1)[1]

'Tablet'